apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops
spec:
  generators:
    - git:
        repoURL: &url https://github.com/tom-stockwell/demo-gitops-cicd.git
        revision: &rev HEAD
        directories:
          - path: 'clusters/cluster/*'
          - path: 'clusters/cluster/gitops'
            exclude: true
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: *url
        targetRevision: *rev
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
