apiVersion: v1
kind: Secret
metadata:
  name: repo-greeting-api
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: greeting-api
  url: https://github.com/tom-stockwell/greeting-api-k8s.git
  type: git
