apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
  params:
    - name: args
      type: array
      default:
        - --version
    - name: image
      type: string
      default: registry.access.redhat.com/ubi8/nodejs-16
  steps:
    - name: script
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      env:
        - name: CI
          value: 'true'
      command:
        - npm
      args:
        - "$(params.args[*])"

