apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tkn-trigger-promote-image
spec:
  params:
    - name: test
      default: test
  steps:
    - name: tkn
      image: $(params.kustomize-step-image)
      workingDir: $(workspaces.source.path)/$(params.kustomize-path)
      env:
        - name: PARAM_VERBOSE
          value: $(params.verbose)
      script: |
        #!/usr/bin/env sh
        set -eu

        if [ "${PARAM_VERBOSE}" = "true" ] ; then
          set -x
        fi
        
        kustomize edit set image "$(params.image-url)@$(params.image-digest)"
