apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quay-deploy
spec:
  params:
    - name: name
    - name: image-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: deploy-$(tt.params.name)-
      spec:
        pipelineRef:
          name: deploy
        params:
          - name: app-name
            value: $(tt.params.name)
          - name: image-url
            value: $(tt.params.image-url)
          - name: git-url
            value: git@github.com:tom-stockwell/$(tt.params.name)-k8s.git
        workspaces:
          - name: scratch
            emptyDir: {}
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
