apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-react
spec:
  params:
    - name: git-revision
    - name: git-repo-name
    - name: git-repo-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-$(tt.params.git-repo-name)-
        labels:
          app: $(tt.params.git-repo-name)
      spec:
        pipelineRef:
          name: ci-react
        params:
          - name: app-name
            value: $(tt.params.git-repo-name)
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-url
            value: quay.io/tstockwell/$(tt.params.git-repo-name)
          - name: image-namespace
            value: tstockwell
          #  only for demo purposes on a private cluster
          - name: mock-webhooks
            value: 'true'
        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: greeting-ui-source
          - name: scratch
            emptyDir: {}
