apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: quay-repo-push
spec:
  params:
    - name: name
      value: $(body.name)
    - name: image
      value: $(body.repository)
    - name: image-url
      value: $(body.docker_url)
    - name: image-namespace
      value: $(body.namespace)
    - name: tags
      value: $(body.updated_tags)
    - name: tag
      value: $(body.updated_tags[0])
