apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quay-deploy
spec:
  params:
    - name: name
    - name: tag
    - name: image-url
    - name: image-namespace
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: deploy-$(tt.params.name)-$(tt.params.tag)-
        labels:
          app: $(tt.params.name)
          environment: $(tt.params.tag)
      spec:
        pipelineRef:
          name: deploy
        params:
          - name: app-name
            value: $(tt.params.name)
          - name: image-url
            value: $(tt.params.image-url)
          - name: image-namespace
            value: $(tt.params.image-namespace)
          - name: git-url
            value: git@github.com:tom-stockwell/$(tt.params.name)-k8s.git
          - name: environment
            value: $(tt.params.tag)
          - name: image-tag
            value: $(tt.params.tag)
          #  only for demo purposes on a private cluster
          - name: mock-webhooks
            value: 'true'
        workspaces:
          - name: scratch
            emptyDir: {}
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
