apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kustomize
spec:
  description: This task can be used to run [kustomize](https://kustomize.io/).
  params:
    - name: args
      type: array
      default:
        - version
      description: The arguments to pass to kustomize.

    - name: path
      type: string
      default: .
      description: >-
        The directory within which kustomize will be run.
        Should be relative to the `source` workspace.

    - name: kustomize-image
      type: string
      default: k8s.gcr.io/kustomize/kustomize:v5.0.0
      description: The image used to run kustomize.

  workspaces:
    - name: source
      description: A workspace that contains kustomizations.

  steps:
    - name: kustomize
      image: $(params.kustomize-image)
      workingDir: $(workspaces.source.path)/$(params.path)
      args:
        - "$(params.args[*])"
      script: |
        set -eux
        kustomize $@


