apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc-greeting-ui-source.yml
  - pvc-greeting-api-source.yml
#  - secret-github.yml
#  - secret-quay.yml
  - serviceaccount-pipeline.yml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: github-webhook-secret
    literals:
      - secret=secret
