apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: github-demo-gitops-cicd-token
  namespace: demo-gitops-cicd-cicd
spec:
  encryptedData:
    token: AgC9lJbmlfXMdB+KO7i9PaeLngR9SEB2IyCFB4cZipDxl5P12CUPa3JZC8KA0rCzzvpkpipyUU5pxirP69Tv51r551/QlSy1KxfIeRO2RBKelc4ADxfu7tkm56xyyQfPtILEmaumnD3uzTznFhXkdSTXpZskMa7zPyNTxCgkK5kfcz6PZZhyz/ViFbOxY/g19+E24c0yD4hKt9qPauJ4dmSQC7+s7F4/jsXJBjxYswfUgn9D00pQFVo7laBMK1jWWWhRxuADCPSMVUlfLOL18K+qIHA+6WksxsQ/ot4jD7ceGtOQhHP6uN3K33YQKvHrqbGBYxHr2ZoGowhBdJaGRfW5wpPVvP4c7QnygJv+c6aYRdrjrQkhGIGkldnmavRq8xJUKSmNEzP2GI11krrY0BgKe+RIjJe/Uwu5xB/36dH1W1zyjig/N6QIQbCJwpS6KCbPAsHeU2W5XwbH372tadoYFqXcPNIHbJ56rVh+1MBPkAcDXQl5T7vIfM/6IulaPEXEHXHGxPJNakgyOumuPOjioRpZADGlm2zF75OFFWJ8BDjr+zQdNYtytzEPehS1aHgFx2u1JVYFiV0kSjBocqVXiL1Q3/BQnSfGs7EchXrZ63HGmjAnaYgSI5+9w0PqNyh6IER/dM0AzvyWs8pq7EoNh6AkATs3lMMyJ+MfRDb4iONWzTfEZNrnhKOu+eHMmj4ouHw30Ge4J/l/zFxw1DbUM4ql/ttwjKIgGw1ekczHcnii3pnQrs67
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: github-demo-gitops-cicd-token
      namespace: demo-gitops-cicd-cicd
    type: Opaque

