apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-react
spec:
  workspaces:
    - name: source
    - name: k8s-source
  params:
    - name: app-name
      type: string
      description: Name of the application

    - name: git-url
      type: string
      description: URL of the git repository containing application source code

    - name: git-revision
      type: string
      default: main
      description: Git revision to checkout application source code

    - name: image-url
      type: string
      description: Container image URL to publish

    - name: image-tag
      type: string
      default: latest
      description: Container image tag to publish

    - name: k8s-git-url
      type: string
      description: URL of the git repository containing k8s manifests

    - name: k8s-git-branch
      type: string
      default: main
      description: Git revision to checkout k8s manifests

    - name: kustomize-path
      type: string
      default: overlays/dev
      description: Directory to update kustomize in

  tasks:
    - name: clean
      taskRef:
        name: script-1001
      workspaces:
        - name: workspace
          workspace: source
      params:
        - name: script
          value: rm -rf node_modules
        - name: workingDir
          value: $(workspaces.workspace.path)

    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter: ['clean']
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)

    - name: install-deps
      taskRef:
        name: npm
      runAfter: ['clone']
      workspaces:
        - name: source
          workspace: source
      params:
        - name: args
          value: ['ci', '--verbose', '--no-audit']

    - name: test
      taskRef:
        name: npm
      runAfter: ['install-deps']
      workspaces:
        - name: source
          workspace: source
      params:
        - name: args
          value: ['test']

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter: ['clone']
      workspaces:
        - name: source
          workspace: source
      params:
        - name: DOCKERFILE
          value: ./Containerfile
        - name: IMAGE
          value: $(params.image-url):$(params.image-tag)

    - name: truncate-digest
      taskRef:
        name: truncate-string
      runAfter:
        - build
      params:
        - name: input
          value: $(tasks.build.results.IMAGE_DIGEST)
        - name: start
          value: '8'
        - name: end
          value: '19'

    - name: k8s-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: k8s-source
      params:
        - name: url
          value: $(params.k8s-git-url)
        - name: revision
          value: $(params.k8s-git-branch)

    - name: update-image
      taskRef:
        name: kustomize-set-image
      runAfter:
        - k8s-clone
        - truncate-digest
        - test
      workspaces:
        - name: source
          workspace: k8s-source
      params:
        - name: image-url
          value: $(params.image-url)@$(tasks.build.results.IMAGE_DIGEST)
        - name: path
          value: $(params.kustomize-path)
        - name: git-branch
          value: $(params.k8s-git-branch)
        - name: git-message
          value: Promote $(tasks.truncate-digest.results.output) to dev
