apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy
spec:
  workspaces:
  - name: source
  - name: scratch

  params:
  - name: app-name
    type: string
    description: Name of the application

  - name: image-url
    type: string
    description: Image url to deploy

  - name: image-tag
    type: string
    default: latest
    description: Image tag to deploy

  - name: environment
    type: string
    default: dev
    description: Environment to deploy to

  - name: git-url
    type: string
    description: URL of the git repository to update

  - name: git-branch
    type: string
    default: main
    description: Branch of the git repository

  - name: git-username
    type: string
    default: ci
    description: Username of the git committer

  - name: git-email
    type: string
    default: ci@example.com
    description: Email of the git committer

  - name: git-primary-message
    type: string
    default: 'Deploy to '
    description: |
      Prefix for first line of the commit message.
      Environment name will be apppended.

  - name: git-secondary-message
    type: string
    default: '- image: '
    description: |
      Prefix for second line of the commit message.
      Image name will be apppended.

  tasks:
  - name: image-digest
    taskRef:
      name: image-digest
    params:
    - name: image
      value: docker://$(params.image-url):$(params.image-tag)

  - name: git-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-branch)

  - name: update-image-ref
    taskRef:
      name: kustomize
    runAfter:
    - git-clone
    - image-digest
    workspaces:
    - name: source
      workspace: source
    params:
    - name: args
      value:
        - edit
        - set
        - image
        - "$(params.image-url)@$(tasks.image-digest.results.digest)"
    - name: path
      value: $(workspaces.source.path)/environments/$(params.environment)

  - name: git-commit
    taskRef:
      name: git-cli
      kind: ClusterTask
    runAfter:
    - update-image-ref
    workspaces:
    - name: source
      workspace: source
    - name: input
      workspace: scratch
    params:
    - name: GIT_USER_NAME
      value: $(params.git-username)
    - name: GIT_USER_EMAIL
      value: $(params.git-email)
    - name: GIT_SCRIPT
      value: |
        git commit -am '$(params.git-primary-message)$(params.environment)' \
          -m '$(params.git-secondary-message)$(params.image-url)@$(tasks.image-digest.results.digest)' || true
        git tag $(params.environment)
        git push origin HEAD:$(params.git-branch)
        git push origin --tags --force

  - name: argo-sync
    taskRef:
      name: argocd-task-sync-and-wait
    runAfter:
    - git-commit
    params:
    - name: argocd-version
      value: v2.2.5
    - name: application-name
      value: $(params.app-name)-$(params.environment)
    - name: revision
      value: $(params.git-branch)
    - name: flags
      value: --insecure

  - name: tag-image-stage
    taskRef:
      kind: ClusterTask
      name: skopeo-copy
    runAfter:
      - argo-sync
    when:
      - input: $(params.environment)
        operator: in
        values: ['dev']
    workspaces:
      - name: images-url
        workspace: scratch
    params:
      - name: srcImageURL
        value: docker://$(params.image-url):$(params.image-tag)
      - name: destImageURL
        value: docker://$(params.image-url):stage

  - name: tag-image-prod
    taskRef:
      kind: ClusterTask
      name: skopeo-copy
    runAfter:
      - argo-sync
    when:
      - input: $(params.environment)
        operator: in
        values: ['stage']
    workspaces:
      - name: images-url
        workspace: scratch
    params:
      - name: srcImageURL
        value: docker://$(params.image-url):$(params.image-tag)
      - name: destImageURL
        value: docker://$(params.image-url):prod
