apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: post-deploy
spec:
  workspaces:
    - name: source
    - name: scratch

  params:
    - name: app-name
      type: string
      description: Name of the application

        - name: image-url
          type: string
          description: URL of the container image to promote.

        - name: image-digest
          type: string
          default: ''
          description: |
            Digest of the container image to promote.
            If not provided, the digest will be extracted from the kustomization file found in `src-path`.

        - name: git-url
          type: string
          description: URL of the git repository containing kustomize manifests to update.

        - name: git-branch-default
          type: string
          default: main
          description: |
            Default branch of the git repository.
            This branch will be checked out when cloning the repository.

        - name: git-branch-push
          type: string
          default: main
          description: |
            Branch of the git repository to push to.
            If this branch is not equal to `git-branch`, a pull request will be created to `git-branch`.

        - name: git-username
          type: string
          default: ci
          description: Username of the git committer

        - name: git-email
          type: string
          default: 101870882+stocky37-robot@users.noreply.github.com
          description: Email of the git committer

        - name: overlays-path
          type: string
          default: overlays
          description: Path to the directory containing the environment overlays.

        - name: src-env
          type: string
          default: ''
          description: |
            The environment to promote the image from.
            This parameter is ignored if `image-digest` is set. 

        - name: dest-env
          type: string
          description: The environment to promote the image to.

  # todo: include smoke tests, system tests, etc.
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-branch-default)

    - name: get-digest
      taskRef:
        name: kustomize-get-digest
      runAfter:
        - clone
      workspaces:
        - name: input
          workspace: source
      params:
        - name: image-name
          value: $(params.image-url)
        - name: path
          value: $(params.overlays-path)/$(params.src-env)

    - name: truncate-sha
      taskRef:
        name: truncate
      runAfter:
        - get-digest
      params:
        - name: input
          value: $(tasks.get-digest.results.digest)
        - name: start
          value: 8
        - name: end
          value: 19

    - name: update-image
      taskRef:
        name: kustomize-set-image
      runAfter:
        - get-digest
      workspaces:
        - name: source
          workspace: source
      params:
        - name: image-url
          value: $(params.image-url)@$(tasks.get-digest.results.digest)
        - name: path
          value: $(params.overlays-path)/$(params.dest-env)
        - name: git-branch
          value: $(params.git-branch-push)
        - name: git-message
          value: Promote $(tasks.truncate-sha.results.output) to $(params.dest-env)

    - name: open-pr
      taskRef:
        name: echo
      runAfter:
        - update-image
      when:
        - input: $(params.git-branch-push)
          operator: notin
          values: ["$(params.git-branch-default)"]
      params:
        - name: args
          value:
            - "Open PR"

