apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: post-deploy
spec:
  workspaces:
    - name: source

  params:
    - name: image-url
      type: string
      description: |
        URL of the container image to promote.
        Should not have a tag or digest.

    - name: git-url
      type: string
      description: URL of the git repository containing kustomize manifests to update.

    - name: git-branch-default
      type: string
      default: main
      description: |
        Default branch of the git repository.
        This branch will be checked out when cloning the repository.

    - name: git-branch-push
      type: string
      default: main
      description: |
        Branch of the git repository to push to.
        If this branch is not equal to `git-branch-default`, a pull request will be created to `git-branch-default`.

    - name: overlays-path
      type: string
      default: overlays
      description: Path to the directory containing the environment overlays.

    - name: src-env
      type: string
      description: The environment to promote the image from.

    - name: dest-env
      type: string
      description: The environment to promote the image to.

  # todo: include smoke tests, system tests, etc.
  tasks:

    ############# MOCK TEST TASKS #############
    - name: clone-tests
      taskRef:
        name: echo
      params:
        - name: args
          value:
            - 'Clone tests repo'

    - name: smoke-tests
      taskRef:
        name: echo
      runAfter:
        - clone-tests
      params:
        - name: args
          value:
            - 'Run smoke tests'

    - name: system-tests
      taskRef:
        name: echo
      runAfter:
        - smoke-tests
      params:
        - name: args
          value:
            - 'Run system tests'

    ############# UPDATE NEXT ENVIRONMENT #############
    - name: clone-k8s
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-branch-default)

    - name: get-digest
      taskRef:
        name: kustomize-get-digest
      runAfter:
        - clone-k8s
      workspaces:
        - name: input
          workspace: source
      params:
        - name: image-name
          value: $(params.image-url)
        - name: path
          value: $(params.overlays-path)/$(params.src-env)

    - name: truncate-sha
      taskRef:
        name: truncate-string
      runAfter:
        - get-digest
      params:
        - name: input
          value: $(tasks.get-digest.results.digest)
        - name: start
          value: '8'
        - name: end
          value: '19'

    - name: update-image
      taskRef:
        name: kustomize-set-image
      runAfter:
        - truncate-sha
        - system-tests
      workspaces:
        - name: source
          workspace: source
      params:
        - name: image-url
          value: $(params.image-url)@$(tasks.get-digest.results.digest)
        - name: path
          value: $(params.overlays-path)/$(params.dest-env)
        - name: git-branch
          value: $(params.git-branch-push)
        - name: git-message
          value: Promote $(tasks.truncate-sha.results.output) to $(params.dest-env)

    - name: open-pr
      taskRef:
        name: echo
      runAfter:
        - update-image
      when:
        - input: $(params.git-branch-push)
          operator: notin
          values: ["$(params.git-branch-default)"]
      params:
        - name: args
          value:
            - "Mock open PR"

