apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test
spec:
  params:
    - name: environment
      type: string
      default: dev

    - name: default-branch
      type: string
      default: main

    - name: pr-branch
      type: string
      default: promote

  tasks:
    - name: script
      taskRef:
        name: script
      params:
        - name: script
          value: |
            set -eux

            case "$(params.environment)" in
              prod) echo -n "$(params.pr-branch)" > $(results.output.path) ;;
              *) echo -n "$(params.default-branch)" > $(results.output.path) ;;
            esac

    - name: echo
      taskRef:
        name: echo
      params:
        - name: args
          value:
            - $(tasks.script.results.output)
