apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-quarkus
spec:
  description: |-
    A CI pipeline for simple quarkus applications.
    
    This pipeline will test the quarkus application before building & publishing a container image.
    A kustomize overlay from the given repository will then be updated with the new image details.
    
    A graph of the pipeline tasks can be seen below:

    ```mermaid
    flowchart LR
        clean-->clone
        clone-->test
        clone-->build
        build-->truncate-digest
        k8s-clone-->update-image
        truncate-digest-->update-image
        test-->update-image
    ```
  params:
    - name: git-url
      type: string
      description: URL of the git repository containing application source code.

    - name: git-revision
      type: string
      default: main
      description: Git revision to checkout for `git-url`.

    - name: image-url
      type: string
      description: >-
        URL of the container image to publish.
        Should not include a tag or digest.

    - name: image-tag
      type: string
      default: latest
      description: Tag of the container image to publish.

    - name: dockerfile
      type: string
      default: ./Containerfile
      description: Path to the Dockerfile to build.

    - name: k8s-git-url
      type: string
      description: URL of the git repository containing k8s manifests.

    - name: k8s-git-branch
      type: string
      default: main
      description: Git revision to checkout for `k8s-git-url`

    - name: overlay-path
      type: string
      default: overlays/dev
      description: Path to the Kustomize overlay to update.

  workspaces:
    - name: source
      description: A workspace to hold the application source code repository.

    - name: k8s-source
      description: A workspace to hold the kustomize repository for the application.

    - name: scratch
      description: A throwaway workspace used for tasks that require a workspace that should be optional.

  tasks:
    - name: clean
      taskRef:
        name: script-185
      workspaces:
        - name: workspace
          workspace: source
      params:
        - name: script
          value: rm -rf target
        - name: workingDir
          value: $(workspaces.workspace.path)

    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter: ['clean']
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)

    - name: test
      taskRef:
        name: maven
        kind: ClusterTask
      runAfter: ['clone']
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: scratch
      params:
        - name: GOALS
          value: ['-B', 'verify']
        - name: MAVEN_IMAGE
          value: registry.access.redhat.com/ubi8/openjdk-17

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter: ['clone']
      workspaces:
        - name: source
          workspace: source
      params:
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: IMAGE
          value: $(params.image-url):$(params.image-tag)

    - name: truncate-digest
      taskRef:
        name: truncate-string
      runAfter:
        - build
      params:
        - name: input
          value: $(tasks.build.results.IMAGE_DIGEST)
        - name: start
          value: '8'
        - name: end
          value: '19'

    - name: k8s-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: k8s-source
      params:
        - name: url
          value: $(params.k8s-git-url)
        - name: revision
          value: $(params.k8s-git-branch)

    - name: update-image
      taskRef:
        name: kustomize-set-image
      runAfter:
        - k8s-clone
        - truncate-digest
        - test
      workspaces:
        - name: source
          workspace: k8s-source
      params:
        - name: image-url
          value: $(params.image-url)@$(tasks.build.results.IMAGE_DIGEST)
        - name: path
          value: $(params.overlay-path)
        - name: git-branch
          value: $(params.k8s-git-branch)
        - name: git-message
          value: Promote $(tasks.truncate-digest.results.output) to dev
