apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app
spec:
  template:
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 3
          backoff:
            duration: 5s    # the amount to back off
            factor: 2       # factor to multiply the base duration after each failed retry
            maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
