apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app
spec:
  template:
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 3
