apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -stage

resources:
  - ../base/applicationset-greeting-app

patches:
  - path: patch-applicationset.yaml
    target:
      kind: ApplicationSet


