apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-push-react
spec:
  interceptors:
    - ref:
        name: github
      params:
        - name: secretRef
          value:
            secretName: github-webhook-secret
            secretKey: secret
        - name: "eventTypes"
          value: ["push"]
    - ref:
        name: cel
      params:
        - name: "filter"
          value: >-
            body.repository.name == "greeting-ui"
  bindings:
    - ref: github-push
      kind: ClusterTriggerBinding
  template:
    ref: ci-react
