apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: argo-postsync
spec:
  params:
    - name: app-name
    - name: environment
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.app-name)-argo-postsync-$(tt.params.environment)-
        labels:
          app: $(tt.params.app-name)
          environment: $(tt.params.environment)
      spec:
        pipelineRef:
          name: argo-postsync
        params:
          - name: app-name
            value: $(tt.params.app-name)
          - name: image-url
            value: quay.io/rh-hcas-emea/$(tt.params.app-name)
          - name: git-url
            value: https://github.com/rh-hcas-emea/greeting-app-k8s.git
          - name: git-repo-full-name
            value: rh-hcas-emea/greeting-app-k8s
          - name: environment
            value: $(tt.params.environment)
          - name: github-token-secret-key
            value: password
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
