apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-react
spec:
  params:
    - name: git-revision
    - name: git-repo-name
    - name: git-repo-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.git-repo-name)-ci-
        labels:
          app: $(tt.params.git-repo-name)
      spec:
        pipelineRef:
          name: ci-react
        params:
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-url
            value: quay.io/rh-hcas-emea/$(tt.params.git-repo-name)
          - name: k8s-git-url
            value: https://github.com/rh-hcas-emea/greeting-app-k8s.git
          - name: overlay-path
            value: overlays/dev/$(tt.params.git-repo-name)

        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: $(tt.params.git-repo-name)-source
          - name: k8s-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
