apiVersion: v1
kind: Secret
metadata:
  name: repo-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: greeting-ui-k8s
  url: https://github.com/tom-stockwell/demo-gitops-cicd-gitops.git
  type: git
