apiVersion: v1
kind: Secret
metadata:
  name: repo-greeting-ui
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: greeting-ui-k8s
  url: https://github.com/tom-stockwell/greeting-ui-k8s.git
  type: git
