apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-digest
spec:
  params:
  - name: image
    type: string
  - name: skopeo-image
    type: string
    default: registry.access.redhat.com/ubi8/skopeo
  results:
  - name: digest
    description: The digest of the given image
  steps:
  - name: inspect
    image: $(params.skopeo-image)
    script: |
      skopeo inspect $(params.image) --format "{{.Digest}}" | tee '$(results.digest.path)'
