apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: quay-webhook
spec:
  params:
    - name: image-name
      type: string
    - name: image-namespace
      type: string
      default: tstockwell
    - name: image-tag
      type: string
      default: latest
    - name: url
      type: string
      default: http://el-greeting-cd-listener:8080
    - name: script-image
      type: string
      default: registry.access.redhat.com/ubi8-minimal
  steps:
    - name: script
      image: $(params.script-image)
      script: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "name": "$(params.image-name)",
            "repository": "$(params.image-namespace)/$(params.image-name)",
            "namespace": "$(params.image-namespace)",
            "docker_url": "quay.io/$(params.image-namespace)/$(params.image-name)",
            "homepage": "https://quay.io/repository/$(params.image-namespace)/$(params.image-name)",
            "updated_tags": ["$(params.image-tag)"]
          }' "$(params.url)"
