apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: script-185
spec:
  workspaces:
    - name: workspace
      optional: true
  params:
    - name: script
      type: string
    - name: image
      type: string
      default: registry.access.redhat.com/ubi8-minimal
    - name: workingDir
      type: string
      default: .
  steps:
    - name: script
      image: $(params.image)
      script: $(params.script)
      workingDir: $(params.workingDir)
      securityContext:
        runAsUser: 185
        runAsNonRoot: true
