apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: argo-postsync
spec:
  params:
    - name: app-name
    - name: environment
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.app-name)-argo-postsync-$(tt.params.environment)-
        labels:
          app: $(tt.params.app-name)
          environment: $(tt.params.environment)
      spec:
        pipelineRef:
          name: argo-postsync
        params:
          - name: image-url
            value: quay.io/tstockwell/$(tt.params.app-name)
          - name: git-url
            value: git@github.com:tom-stockwell/$(tt.params.app-name)-k8s.git
          - name: repo-full-name
            value: tom-stockwell/$(tt.params.app-name)-k8s
          - name: environment
            value: $(tt.params.environment)
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
