apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc-greeting-ui-source.yml
  - pvc-greeting-api-source.yml
  - secret-argocd-env-secret.yml
  - secret-github-demo-gitops-cicd-token.yml
  - secret-github-stocky37-robot.yml
  - secret-tstockwell-quay.yml
  - serviceaccount-pipeline.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: argocd-env-configmap
    literals:
      - ARGOCD_SERVER=openshift-gitops-server-openshift-gitops.apps.paas.lab.stocky37.dev

secretGenerator:
  - name: github-webhook-secret
    literals:
      - secret=secret
