apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tstockwell-quay
  namespace: demo-gitops-cicd-cicd
spec:
  encryptedData:
    password: AgB827DKaHLjTPEY5SaDGag4m2aiw/q29BR6fWCOY1uKC5hHNCWefrP9rsIWZkn95ZEJV+3dp/mWcjIGSwEWcf2AIee2NJc+ghFmLhkQDaT17kwKt+6mL2u1xVySKZZiQ0JWnbPszdeuAvSowmLxF5kmPowWUECzqAK5bDIREQbk79KC/adoco+7+8ISTCmuC2L8vwon5bA7uzucKN5YhjVorlZ6KAwtGthM67NVeAx2ZNLGtZMHxZg+1XYqysQEa+swv2wg5iJVg0RVV4WjXwq3KK6973pi9JYNgvkEQRtYReE7Rc9fRpNnFD6zinW5GN+BcjWnHM++M3TzypXigQKFh81DSzetUWyDVgxstyB4nfsMIqoZUwPLfLOkHJF2YgZVSbAGFtq4/ftEbhKkb5LB0c4SIbcOT/r/ub+hVwKTE7GEDV4kr+OWhSYeWjRq/iuWc/RIopDIOLihOSbphG98UECiXz2/W7PT1WuFV1u+EyjqXqAPn+0R5+8mI1IaEe/okFC1T82YFsIwupeMAoMYmGGiXxSDvw1gTGP8KCXWI0iB1Q1IQgpAuM78ZuKJ8Cw613jFTyN31p3bnkifxOqqIacLPMFbq+NO6t5bOlv93j6lBDxFCKh72/9NEUKzsUNE7dgqHI8Cal0jr4fgprJxiJpU/XP8c5MOx9cQPDv6vi05l0RFj1NTfr3JbAbQXPRcY9Tqc9SDAtxeVJvvMs0lH0pntJc/B3kPzI3B6V1qRQ7Ykp5nnSLBkxaQ++D5ZqCSU8BjSuXHw5BNSriivq31
    username: AgClvT/0zSujStq8DA1zIq59L9+cFK2pLHWvLkWTtD94u9rrbpaIMMIBtQAJHfaWcvs7btAz/enex93Ds5FFDArfXyz0xBtZanEWujiTiIONOSn2xGsU/ytm6mU9eYBNsQ/6WGKYoiKr0EjFpmX7A21PzXJ8KPQYkZgvLgbs9JP6x0X4d21ySeeFZ9Eg5pOyYe09btmeCDNRd1SwKSevWG8aiuX+4076DnV6q514htxBYlnlMhfMEfTbHNi2XirxvW70cNrEt5v8wsetqW1vKB4WOidnQyb3OgWcLxUUP3MiTWwhJLQwNnM+F8V0Jj+HvkirX7tuzTsGJf6otOCQqVM9GAOt6bW693sI1Fi7BeTD6h+4fKuIoyyjWNdPD9Qf/vfluuqzu1UDGgyP26nvKCMiPPZwZ0f7J4PDf1oRUrrrdZMCXE/bWcqHFFDLlVpTCqVibJakfZKC+PwtvrFHRDDD+EVyP8BhSlZQuyQDPPHDChfI6jJE1RYc86v24rmLbUkRkH7BI8qcLKfSVlPPwNswlhDFndYno8n9KRzswS7SL9Kmy1M8He0MP/0kClgHosSXhV74oBKTI+PXXQpd9OQC3ggVGntMRxi0d0/slwJ+4y4WnXTR6jYSNFhWHV0z4feZ9kY5mfecIdR2OrUaxOX8MiXH7fOLO6V5V0cyl+tWPfSS7edKB5c/f7I6Phf7dFXD54beo6Eci3eBUVOi57Ji7Q==
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/docker-0: quay.io
      creationTimestamp: null
      name: tstockwell-quay
      namespace: demo-gitops-cicd-cicd
    type: kubernetes.io/basic-auth

