apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-argocd-env-secret.yml
  - secret-greeting-ui-github.yml
  - secret-tstockwell-quay.yml
  - serviceaccount-pipeline.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: argocd-env-configmap
    literals:
      - ARGOCD_SERVER=openshift-gitops-server-openshift-gitops.apps.paas.lab.stocky37.dev
