apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tstockwell-quay
  namespace: examples-cicd
spec:
  encryptedData:
    password: AgC6oV3bL0hgtbUTn60NPgeObKFYYeSO26sZc8hYLnDInHNP6jZITQ9w9E6z+CVfPMruv3GqT8Kmvf/MGqBOsDTBRNXjJYXSsgC5bsd3pK+8DPGHaNkzcEJQlyngMZpeRFC5j4Rsiw2xc3V/9gIacOwkL9eeNY9BAkpd2Lkl0jGZD9Sm2lfKiCTIT/oVIuYT50f8IWYhJEKnsSwmHrgLYPJqo+sr7hC7EnFtEyIhYv2sPkwP8PCOhSrhx80+O0Uvq5CZKJJP5f9fBZPWUeTBQzKOeoL6H/HOuF+9y/q2DgLj5/Mz2kmZf0bL4INqYikD8EtN8HYR07clQ4NyaLX7ds46IPTq9l1gkFEn3q8wMQVEJ+1C2cwcZqy7znliX8tYS/YzoIGz7gY0E1LjGDDc8ZOcCBIGPX0Flx6WF16sfr3ZEFmdfKxqaarEc7isU1XHFxOKe8koFz9HCzyqztHID9DtV02WgyeB2FDVvWAVRNqASuXqiBS2MJoGpgndJza3BNuJT/0Vwnw/PGKY5iTgkNuK3OnB/OE6HCBjO/uaIuZ/lbuH80kGU+hFopLyRW6Ueh7SgKZ4vhdFdzZy9kYuAPFBa7XH48FmhxtwG9hBX/jKADdzwv4/VnzkAypmcjOAL3gUp/YqCoeTOwH6eYjGNYiTjI+eCuMf2G3YZnx6nTV1PZ6gT9TAwPvRxGN71rJ9gSejPlZTwnjrRZX8adep9U3Enmbh9EP6K3CuEEfzCWlbeggED1XnRjtGO28sNRVT7jgw9BP5rSUK7KwVJ43+JzOP
    username: AgB+4mC7gFGhXY1SpyeCogH32wp0afcEM90EpPmffGbstl4IUNX0jtWzx1mn+haMj++eaqFbN8TK2A2fwXbygnKjxz35UX8xacFFmhA7+nDngCvuqSFPQEP4WP4lK2pORPcyNojgwjmCRzp/aj1dS/WOO6TJ5BbADJRLRonRJBmT4N3QvgXmcpUEyA6sRij5GEEGdDg1hdQ3YZ7zZMplQB7lupaOfJ8WFlj/9JLWTakMoIbdvWj6LDEaS12jGuS34pkyM74N6pGr1wBD3VelIDV4wxyo0yr3hU/S+xDCYMdIsol6Yywh/5MjiZeU9wOrJQ7dBCcIT18qR2GaW5bYlYAi0uxp8PZMIMzzZFAKqa1Y9RII3+i/8KbBhhsRq2CwKSb3b4v46Qd0mP5aIy1m/6nL935MVVGvjz9bkHcpTlnh5cMvFpF9MLVs5OqyBgEnIBceTyBCevJNP6R0o0rxPLeC5VtKc5k0qO36hxmOYEICfQfdqFJark1P7/I6iimdVt9lyP33wtniz0uolB/7zYfo2ZdWna4xU35ywUfQfOCPGaJFbdoNUEzavMOVOHdFrgyb++lhdVhszvVEH2D66R8Igs8hg9GnraI1ZqVbWLs1zeF8fKcMEHXjtUXLZAp64jToAqLCSqMpZYuYtRjl94TpsrQ/ANDYqnO+31UZs8ERyYDRRnRexzLOohwRU4ClWc9WZ0dnaB9dd8obMDYMm++4Sw==
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/docker-0: quay.io
      creationTimestamp: null
      name: tstockwell-quay
      namespace: examples-cicd
    type: kubernetes.io/basic-auth

