apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-demo-gitops-cicd-token
  namespace: demo-gitops-cicd-cicd
spec:
  encryptedData:
    token: AgCfnR50RdX1VqXuGCrNUMG7kY136zxsHkl+WuZL/LYi3yExgNed+t6jvvH3W2imri77/tqAmTLlT/uhq9hXbNDlls4au61NoWCZCBeQsR7WHYEbmN8LYRKQkbRD7Gqrxx1Tu4Uag8/xFX2IZBx6RyyQRHQVC/71WPbSAj4FMJjy4gwgJdEhbOslSLeH/TpVD8Ufa5AI/8imOg4/c5f17ZocI0QJU+UJLtFbpCmop714FTM7omEOWyn/3pStQzWpJ14T0424ykRPK8cbmA7L3ZQqt/h2yAtr/xlfetN9reFG3EXzPF76WFGMZycXjsBM2BAL4lHOAVqHwB2SIFlZ+wOaKGNIopG4Z3s6jiG47XKRuygcOLDKC/SJCsc1cZO2u9GZRjcpdsYkfMWmyEMUgIcVIK4hthlBFJq89QJBwHDWnF2pw/UNIALqpH3UPzYdqSpVP7YRGFC0AR3W1eARBA0CAC8O38Djyl6JSYJLC0FD6j+zTAE++pP0X7x/P1iAjvDHLlDskG12mW0ioXfPob0uPkFdj2zBMzDa124vkFI50/4zk7gPEjSWabYBE6W7GtiCgLgi2jjQKm9RN4clNPWwd5TIIgtcNPmD1UvGJ9kvCJgw0mGC0w/pT75tQObippPqG7YkTk9nltpXctUWvO6Rr71Y6r9Qcv3mUPGjTYImuP9Qxd8XQUpI7V96XkexuVcPb0LefqFYw0vMXL3+SFE2Mgm5takh3o4JMD8lHEnxxUy297+aOTIv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-demo-gitops-cicd-token
      namespace: demo-gitops-cicd-cicd
    type: Opaque

